Repository chrisj117/CS-472-GROUP-2-PROJECT, pull requests merged in 2023-10, with the labels that each got.

#19 Frontend setup
  web/.eslintrc.cjs
  web/index.html
  web/package-lock.json
  web/package.json
  web/public/vite.svg
  web/src/App.jsx
  web/src/assets/react.svg
  web/src/index.css
  web/src/main.jsx
  web/vite.config.js
Labels: frontend

#16 Setup Docker and Docker Compose
  CONTRIBUTING.md
  LICENSE
  README.md
  api/.dockerignore
  api/Dockerfile
  api/requirements.txt
  docker-compose.yaml
  web/.dockerignore
  web/Dockerfile
  web/vite.config.js
Labels: read for review

#21 CI Pipeline and Unittesting Setup
  .github/workflows/ci.yaml
  README.md
  api/.coveragerc
  api/.gitkeep
  api/requirements.txt
  api/setup.cfg
  api/utils/.gitkeep
  api/utils/__init__.py
  api/utils/setup_test.py
Labels: read for review

#27 Created UNLV Course CSV, Included scrape.py
  data/UNLV Courses/courses.csv
  data/UNLV Courses/scrape.py
Labels: read for review, backend

#26 Update Frontend Dependencies
  web/package-lock.json
  web/package.json
  web/postcss.config.js
  web/src/App.jsx
  web/src/components/Content.jsx
  web/src/components/Navbar.jsx
  web/src/components/Searchbar.jsx
  web/src/index.css
  web/src/main.jsx
  web/src/pages/Home.jsx
  web/src/pages/NotFound.jsx
  web/tailwind.config.js
Labels: refactor, read for review, frontend

#23 Created basic issue template
  .github/ISSUE_TEMPLATE/general-issue-template.md
Labels: documentation

#25 Created pull request template
  docs/pull_request_template.md
Labels: documentation
