Repository chrisj117/CS-472-GROUP-2-PROJECT, pull requests merged in 2023-12, with the labels that each got.

#124 Request School page mobile responsiveness
  web/src/pages/RequestSchool.jsx
Labels: read for review, frontend

#130 Hot-Fix: Static Username in Registration Message
  api/authentication/views.py
Labels: bug, read for review, backend

#133 About Page Mobile Responsiveness
  web/src/pages/About.jsx
Labels: refactor, frontend

#139 Hotfix: Upload course data
  api/build.sh
Labels: read for review, backend

#140 Hotfix: Codecov
  .github/workflows/ci.yaml
Labels: read for review

#136 Add Professor Model and Update Review Model with New Fields and Professor Relationship
  api/backend/urls.py
  api/review/admin.py
  api/review/migrations/0004_review_professor.py
  api/review/migrations/0005_review_rating_clarity_requirements_and_more.py
  api/review/models.py
  api/review/serializers.py
  api/review/views.py
  api/school/admin.py
  api/school/migrations/0007_professor_course_professors.py
  api/school/models.py
  api/tests/test_models.py
  api/tests/test_views.py
Labels: enhancement, backend

#152 Searchbar & Request School 1
  web/src/components/Searchbar.jsx
  web/src/components/example.jsx
  web/src/main.jsx
  web/src/pages/Course.jsx
  web/src/pages/Home.jsx
  web/src/pages/Login.jsx
  web/src/pages/PasswordReset.jsx
  web/src/pages/Profile.jsx
  web/src/pages/Register.jsx
  web/src/pages/RequestSchool.jsx
  web/src/pages/School.jsx
  web/src/tests/regexTest.test.js
  web/src/utilities/API.jsx
  web/src/utilities/GetData.jsx
  web/src/utilities/RegexTest.jsx
Labels: bug, enhancement, frontend

#150 Add courses endpoint
  api/.env-example
  api/.gitkeep
  api/UNLV_course_data/courses_with_professors.csv
  api/backend/urls.py
  api/school/.env-example
  api/school/serializers.py
  api/school/views.py
  web/.gitkeep
Labels: read for review, backend

#151 doc: add more design diagrams
  docs/img/UC-Authentication.jpg
  docs/img/UC-Authentication.pdf
  docs/img/UC-Request-School.jpg
  docs/img/UC-Request-School.pdf
  docs/img/UC-Search School.pdf
  docs/img/UC-SearchSchool.jpg
Labels: documentation

#153 Login + Register Page Responsiveness
  web/src/pages/Login.jsx
  web/src/pages/Register.jsx
Labels: enhancement, frontend

#154 Searchbars & School Page Complete
  web/src/components/CourseCard.jsx
  web/src/components/Searchbar.jsx
  web/src/index.css
  web/src/main.jsx
  web/src/pages/Home.jsx
  web/src/pages/RequestSchool.jsx
  web/src/pages/Root.jsx
  web/src/pages/School.jsx
  web/src/utilities/GetData.jsx
Labels: feature, frontend

#157 Updated Review.jsx mobile vertical dark mode
  web/src/pages/Review.jsx
Labels: bug, frontend

#155 Hotfix: Update Input Styles in Dark Mode
  web/src/components/InputField.jsx
  web/src/pages/Profile.jsx
Labels: refactor, frontend

#159 Updated Review.jsx Dropdown Text
  web/src/pages/Review.jsx
Labels: bug, frontend

#161 Integrate review model with frontend
  web/package.json
  web/src/components/CourseCard.jsx
  web/src/components/RatingBar.jsx
  web/src/components/Searchbar.jsx
  web/src/main.jsx
  web/src/pages/Review.jsx
  web/src/pages/School.jsx
Labels: feature, frontend

#163 Final Touchups & Deployment
  web/package-lock.json
  web/src/components/CourseCard.jsx
  web/src/components/RatingBar.jsx
  web/src/components/ReviewCard.jsx
  web/src/components/Searchbar.jsx
  web/src/main.jsx
  web/src/pages/Home.jsx
  web/src/pages/Review.jsx
  web/src/pages/School.jsx
  web/src/utilities/GetData.jsx
Labels: enhancement, frontend

#164 Hotfix: Icon, Title, Deployment
  web/index.html
  web/public/grad.svg
  web/public/vite.svg
  web/src/utilities/Axios.jsx
Labels: frontend, backend

#167 Review Rating Button
  web/src/components/ReviewCard.jsx
  web/src/pages/Review.jsx
  web/src/utilities/PostData.jsx
Labels: feature, frontend
