Repository chrisj117/CS-472-GROUP-2-PROJECT, pull requests merged in 2023-11, with the labels that each got.

#34 Setup Frontend Testing
  web/.gitignore
  web/package-lock.json
  web/package.json
  web/src/App.jsx
  web/src/components/Card.jsx
  web/src/components/Content.jsx
  web/src/components/example.jsx
  web/src/main.jsx
  web/src/pages/About.jsx
  web/src/pages/Course.jsx
  web/src/pages/RequestSchool.jsx
  web/src/pages/Review.jsx
  web/src/pages/Root.jsx
  web/src/pages/School.jsx
  web/src/tests/example.test.js
  web/vite.config.js
Labels: frontend

#33 Home Page Appearance Setup
  web/src/pages/Home.jsx
Labels: read for review, feature, frontend

#48 Clean up JSX syntax in Home.jsx and set it as index page of website
  web/src/main.jsx
  web/src/pages/Home.jsx
Labels: bug, feature, frontend

#49 Created navbar and request school page
  web/src/components/Navbar.jsx
  web/src/pages/RequestSchool.jsx
Labels: feature, frontend

#30 Endpoints for School
  .github/workflows/ci.yaml
  README.md
  api/.gitignore
  api/backend/settings.py
  api/backend/urls.py
  api/requirements.txt
  api/school/__init__.py
  api/school/admin.py
  api/school/apps.py
  api/school/migrations/0001_initial.py
  api/school/migrations/0002_alter_school_long_name_alter_school_short_name.py
  api/school/migrations/0003_alter_school_long_name_alter_school_short_name.py
  api/school/migrations/0004_alter_school_created_at.py
  api/school/migrations/0005_school_website.py
  api/school/migrations/__init__.py
  api/school/models.py
  api/school/serializers.py
  api/school/tests.py
  api/school/views.py
  api/tests/__init__.py
  api/tests/test_models.py
  api/tests/test_views.py
  api/utils/models.py
  api/utils/views.py
Labels: read for review, feature

#32 Added corsheaders configuration to settings.py
  api/backend/settings.py
  api/requirements.txt
Labels: refactor, backend

#50 About Page Setup
  web/src/pages/About.jsx
Labels: read for review, feature, frontend

#56 Home Page: Removed redundant navbar & created Question-Answer component
  web/src/components/QA.jsx
  web/src/pages/Home.jsx
Labels: bug, frontend

#55 Review Page Partial Setup
  api/backend/settings.py
  web/src/main.jsx
  web/src/pages/Review.jsx
Labels: read for review, work in progress, feature, frontend

#60 Created "Not Found" page
  web/src/components/Navbar.jsx
  web/src/components/ReturnHome.jsx
  web/src/pages/About.jsx
  web/src/pages/NotFound.jsx
Labels: bug, feature, frontend

#51 School Search Bar 1
  .github/workflows/ci.yaml
  web/src/components/Searchbar.jsx
  web/src/pages/Home.jsx
  web/src/utilities/schools.jsx
Labels: feature, frontend

#71 feat(docs): add architectural diagrams
  docs/img/sequence_diagram.jpg
  docs/img/usecase_diagram.jpg
Labels: documentation, read for review

#54 Request School API (GET, POST, DELETE)
  api/backend/settings.py
  api/backend/urls.py
  api/requestschool/__init__.py
  api/requestschool/admin.py
  api/requestschool/apps.py
  api/requestschool/migrations/0001_initial.py
  api/requestschool/migrations/0002_alter_requestschool_school_name.py
  api/requestschool/migrations/__init__.py
  api/requestschool/models.py
  api/requestschool/serializers.py
  api/requestschool/tests.py
  api/requestschool/views.py
  api/tests/test_models.py
  api/tests/test_views.py
Labels: read for review, feature, backend

#77 Upload PR Review Guideline to Repo
  CONTRIBUTING.md
  docs/PR-CHECKLIST.md
Labels: documentation

#68 Endpoints for Reviews
  api/backend/settings.py
  api/backend/urls.py
  api/review/__init__.py
  api/review/admin.py
  api/review/apps.py
  api/review/migrations/0001_initial.py
  api/review/migrations/__init__.py
  api/review/models.py
  api/review/serializers.py
  api/review/tests.py
  api/review/views.py
  api/tests/test_models.py
  api/tests/test_views.py
Labels: read for review, feature, backend

#63 School Page Features 1
  web/.eslintrc.cjs
  web/src/components/CourseCard.jsx
  web/src/components/QA.jsx
  web/src/components/Searchbar.jsx
  web/src/components/SquareRating.jsx
  web/src/main.jsx
  web/src/pages/Home.jsx
  web/src/pages/School.jsx
Labels: feature, frontend

#72 Frontend Styling Overhaul
  web/src/components/Navbar.jsx
  web/src/components/QA.jsx
  web/src/components/RatingBar.jsx
  web/src/components/ReturnHome.jsx
  web/src/components/ReviewCard.jsx
  web/src/index.css
  web/src/pages/About.jsx
  web/src/pages/Home.jsx
  web/src/pages/NotFound.jsx
  web/src/pages/RequestSchool.jsx
  web/src/pages/Review.jsx
  web/src/pages/School.jsx
Labels: refactor, frontend

#73 Course page 3
  web/src/components/Navbar.jsx
  web/src/components/RatingBar.jsx
  web/src/components/ReviewCard.jsx
  web/src/components/SquareRating.jsx
  web/src/index.css
  web/src/pages/NotFound.jsx
  web/src/pages/RequestSchool.jsx
  web/src/pages/Review.jsx
Labels: refactor, frontend

#78 Update Workload.ipynb
  docs/charts/Workload.ipynb
Labels: documentation

#74 Automatic API documentation with Swagger UI
  README.md
  api/backend/settings.py
  api/backend/urls.py
  api/requirements.txt
  api/school/views.py
Labels: documentation, read for review, backend

#79 Support `short_name` alongside `UUID` in POST and PUT Endpoints
  api/review/views.py
  api/tests/test_views.py
Labels: enhancement, backend

#81 Extended Review Model
  api/review/admin.py
  api/review/migrations/0002_review_recommended_review_textbook_required_and_more.py
  api/review/models.py
  api/tests/test_models.py
Labels: enhancement, backend

#96 [deploy] Continuous Deployment of Backend API using Vercel
  api/backend/settings.py
  api/backend/wsgi.py
  api/build.sh
  api/vercel.json
Labels: read for review

#97 Initial Course Model
  api/school/migrations/0006_course.py
  api/school/models.py
  api/tests/test_models.py
Labels: feature, backend

#102 Frontend Authentication Setup
  web/src/components/Navbar.jsx
  web/src/main.jsx
  web/src/pages/Login.jsx
  web/src/pages/Register.jsx
Labels: frontend

#110 Dev and Production Environment Separation
  api/backend/settings.py
  api/build.sh
  api/requirements.txt
Labels: read for review, backend

#94 [auth] User registration verification and login
  api/authentication/__init__.py
  api/authentication/admin.py
  api/authentication/apps.py
  api/authentication/migrations/0001_initial.py
  api/authentication/migrations/__init__.py
  api/authentication/models.py
  api/authentication/renderers.py
  api/authentication/serializers.py
  api/authentication/tests/__init__.py
  api/authentication/tests/test_model.py
  api/authentication/tests/test_setup.py
  api/authentication/tests/test_views.py
  api/authentication/utils.py
  api/authentication/views.py
  api/backend/settings.py
  api/backend/urls.py
  api/build.sh
  api/requirements.txt
  api/school/.env-example
  api/vercel.json
Labels: read for review, backend

#115 Create Login Page
  web/src/pages/Login.jsx
Labels: feature, frontend

#114 Create Registration Page
  web/src/pages/Register.jsx
Labels: read for review, frontend

#116 Responsive Navbar and Hamburger Menu
  web/src/components/Navbar.jsx
Labels: feature, frontend

#120 InputField component for tidying up Login & Register pages
  web/src/components/InputField.jsx
  web/src/pages/Login.jsx
  web/src/pages/Register.jsx
Labels: refactor, frontend

#113 Updated Review Endpoints
  api/review/admin.py
  api/review/migrations/0003_review_course.py
  api/review/models.py
  api/review/serializers.py
  api/review/views.py
  api/tests/test_models.py
  api/tests/test_views.py
Labels: enhancement, read for review, backend

#121 Light Dark Mode Toggle
  web/src/components/Navbar.jsx
  web/src/components/QA.jsx
  web/src/index.css
  web/src/pages/Home.jsx
  web/src/pages/Login.jsx
  web/src/pages/Register.jsx
  web/src/pages/RequestSchool.jsx
  web/src/pages/Root.jsx
  web/tailwind.config.js
Labels: feature, frontend

#122 FIX: Api deployment
  api/Dockerfile
  api/authentication/views.py
  api/backend/settings.py
  api/build.sh
  api/requirements.txt
  api/staticfiles/.gitkeep
  api/staticfiles/plain.txt
  api/vercel.json
Labels: bug, backend

#117 Backend authentication completed
  api/authentication/serializers.py
  api/authentication/tests/test_setup.py
  api/authentication/tests/test_views.py
  api/authentication/utils.py
  api/authentication/views.py
  api/backend/settings.py
  api/backend/urls.py
Labels: read for review, backend

#123 Home page mobile responsiveness
  web/src/pages/Home.jsx
Labels: read for review, frontend
